# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues

newIssueWelcomeComment: >
  Hello there! 👋🏻 
  
  Thank you and congrats 🎉 for opening your very first issue in this project. 
  Feel free to get in touch with [Sonu](https://flyingsonu122.netlify.app/) to become a part of our Community.  Hope to see you there!😄
  
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository

newPRWelcomeComment: >
  Hello there! 👋 Welcome to the project! 💖
  
  Thank you and congrats 🎉 for opening your first pull request.  We will get back to you as soon as we can. 😄
   
  Feel free to get in touch with  [Sonu](https://flyingsonu122.netlify.app/) to become a part of our Community. Hope to see you there!😄
  
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
  Congrats on merging your first Pull Request! 🎉 All the best for your amazing open source journey ahead. 🚀⚡️
